# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_Orders.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Orders(object):
    def setupUi(self, Form_Orders):
        Form_Orders.setObjectName("Form_Orders")
        Form_Orders.resize(779, 498)
        self.groupBox_CurrentOrders = QtWidgets.QGroupBox(Form_Orders)
        self.groupBox_CurrentOrders.setGeometry(QtCore.QRect(10, 10, 761, 191))
        self.groupBox_CurrentOrders.setObjectName("groupBox_CurrentOrders")
        self.tableView_CurrentOrders = QtWidgets.QTableView(self.groupBox_CurrentOrders)
        self.tableView_CurrentOrders.setGeometry(QtCore.QRect(10, 20, 651, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView_CurrentOrders.setFont(font)
        self.tableView_CurrentOrders.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_CurrentOrders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_CurrentOrders.setObjectName("tableView_CurrentOrders")
        self.tableView_CurrentOrders.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_CurrentOrders.verticalHeader().setCascadingSectionResizes(False)
        self.pushButton_CancelOrder = QtWidgets.QPushButton(self.groupBox_CurrentOrders)
        self.pushButton_CancelOrder.setGeometry(QtCore.QRect(670, 150, 81, 31))
        self.pushButton_CancelOrder.setObjectName("pushButton_CancelOrder")
        self.groupBox_HistoricalOrders = QtWidgets.QGroupBox(Form_Orders)
        self.groupBox_HistoricalOrders.setGeometry(QtCore.QRect(10, 210, 761, 241))
        self.groupBox_HistoricalOrders.setObjectName("groupBox_HistoricalOrders")
        self.tableView_HistoricalOrders = QtWidgets.QTableView(self.groupBox_HistoricalOrders)
        self.tableView_HistoricalOrders.setGeometry(QtCore.QRect(10, 20, 741, 211))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView_HistoricalOrders.setFont(font)
        self.tableView_HistoricalOrders.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_HistoricalOrders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_HistoricalOrders.setObjectName("tableView_HistoricalOrders")
        self.tableView_HistoricalOrders.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_HistoricalOrders.verticalHeader().setCascadingSectionResizes(False)
        self.pushButton_Hide = QtWidgets.QPushButton(Form_Orders)
        self.pushButton_Hide.setGeometry(QtCore.QRect(680, 460, 93, 31))
        self.pushButton_Hide.setObjectName("pushButton_Hide")
        self.pushButton_Refresh = QtWidgets.QPushButton(Form_Orders)
        self.pushButton_Refresh.setGeometry(QtCore.QRect(10, 460, 93, 31))
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")

        self.retranslateUi(Form_Orders)
        QtCore.QMetaObject.connectSlotsByName(Form_Orders)

    def retranslateUi(self, Form_Orders):
        _translate = QtCore.QCoreApplication.translate
        Form_Orders.setWindowTitle(_translate("Form_Orders", "Orders"))
        self.groupBox_CurrentOrders.setTitle(_translate("Form_Orders", "Current Orders"))
        self.pushButton_CancelOrder.setText(_translate("Form_Orders", "Cancel"))
        self.groupBox_HistoricalOrders.setTitle(_translate("Form_Orders", "Historical Orders"))
        self.pushButton_Hide.setText(_translate("Form_Orders", "Hide"))
        self.pushButton_Refresh.setText(_translate("Form_Orders", "Refresh"))
